### ISSUE TITLE
Deploy with Workers Failing

### ISSUE THREAD

**Issue by some-guy-23** [LeoColomb/dispoflare#271] opened 2024-02-29 19:48 UTC
Attempting to deploy this, going through each step, but something seems to fail trying to create the Github Actions / deployment, as nothing is actually created in my forked repo (even though I enabled actions). I get to final step on Cloudflare Worker deploy page and it just says "initializing" then "error" with no other details.

Does latest version work for anyone else?

**Comment by LeoColomb** [comment] 2024-02-29 23:01
Thanks for opening this issue, @some-guy-23.

> Cloudflare Worker deploy page and it just says "initializing" then "error" with no other details

Would you mind posting a screenshot?

**Comment by LeoColomb** [comment] 2024-03-01 22:39
This is quite difficult to diagnostize, and I'm unable to reproduce.
I'm suggesting the following:
* Delete your fork
* Try the process again
* Before submitting the last step, open the developer panel of your browser and open the Network tab
  * If the process succeeds, great, you can close the dev panel and this issue.
  * If the error happens again, click on the last request made in the network tab and post here the response.

**Comment by some-guy-23** [comment] 2024-03-02 18:49
Attempted to run the process again, checked last few API calls going to GitHub -

1. POST to `/dispatches` with payload of `event_type: "deploy_to_cf_workers"` ✔
2. GET for `/actions/workflows` properly returns the deploy workflow info and ID ✔
3. GET for `/runs` for the workflow ID above, successful response, but returns no active runs (empty array) ⚠
4. GET for `/repos/undefined/actions/workflows/undefined/runs` returns a 404 error ❌

Hope this helps! It seems like for whatever reason that initial dispatches event isn't kicking off the deploy run?

**Comment by LeoColomb** [comment] 2024-03-02 22:44
Great, thanks for your reply and the details. 
That leads me to a guess, and I believe it should be fixed now. 
Could you try the full process one last time? Don't forget to delete your fork first 😊

**Comment by LeoColomb** [comment] 2024-03-04 14:31
Ah, that's cool!
I just don't really understand why it was working 3–4 months ago but not anymore.
For the best I guess, and thanks for your replies.

> I might suggest (but totally up to you) is filter event types like so?

Good idea! Would you like to open a pull requet?

> Think you can close the issue now,

Closing

**Closed by LeoColomb** 2024-03-04 14:31 UTC
Labels: bug

**Comment by silentresearch** [comment] 2024-04-30 00:00
I'm having the exact same issue.
